function writable(){if(istArchiv()){toast('Dieser Archivstand ist schreibgeschützt. Erstelle eine Arbeitskopie.');return false;}return true;}
function serviceDialog(){if(!writable())return;modal('Dienstleistung einrichten',`<div class="form-grid">${formField('name','Bezeichnung',S.name)}${formField('unit','Einheit',S.settings.eigeneEinheit)}${formField('start','Beginn der Dienstleistung',S.service.start,'date')}${formField('end','Ende der Dienstleistung',S.service.end,'date')}<label class="field wide"><span>Planungsnotiz</span><textarea id="field-note">${esc(S.service.note)}</textarea></label></div>`,[{t:'Abbrechen'},{t:'Speichern',primary:true,fn:()=>{if(!field('name'))throw Error('Bitte eine Bezeichnung eingeben.');if(field('start')&&field('end')&&field('end')<field('start'))throw Error('Das Ende liegt vor dem Beginn.');S.name=field('name');S.settings.eigeneEinheit=field('unit');S.service={...S.service,start:field('start'),end:field('end'),note:field('note')};afterChange();}}]);}
function personDialog(id){
  if(!writable())return;const returnToPlanning=UI.view==='groups'||UI.view==='home';const p=pById(id),data=p||{name:'',grad:'',pnr:'',funktion:'',planning:{status:'unreviewed',reason:''}};
  modal(p?'Teilnahme & Zuteilung':'Person erfassen',`${p&&directGroups(p.id).length>1?'<div class="notice">Mehrere bisherige direkte Zuteilungen: '+directGroups(p.id).map(d=>esc(d.ec||d.name)).join(', ')+'. Beim Speichern bleibt nur das ausgewählte Hauptdetachement. Weitere EC bei der Gruppe als Zusatz-MB verknüpfen.</div>':''}<div class="form-grid">${formField('person-name','Name / Vorname',data.name)}${formField('person-grad','Grad',data.grad)}${formField('person-pnr','Versicherten-Nr.',data.pnr)}${formField('person-function','Funktion',data.funktion)}<label class="field"><span>Teilnahmeentscheid</span><select id="field-status">${[['unreviewed','Teilnahme klären'],['included','Einplanen'],['excluded','Nicht einplanen']].map(([v,t])=>`<option value="${v}" ${participation(data)===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span>Detachement</span><select id="field-main"><option value="">Noch nicht zugeteilt</option>${S.dets.map(d=>`<option value="${esc(d.id)}" ${p&&directGroups(p.id)[0]?.id===d.id?'selected':''}>${esc(d.name)}${d.ec?' · '+esc(d.ec):''}</option>`).join('')}</select></label><label class="field wide"><span>Begründung / Planungsnotiz (bei «Nicht einplanen» erforderlich)</span><textarea id="field-reason">${esc(data.planning.reason)}</textarea></label>${data.identityReview?`<label class="check wide"><input type="checkbox" id="identityConfirmed"><span>Identität und Versicherten-Nr. mit der Quelle geprüft: ${esc(data.identityReview)}</span></label>`:''}</div><div class="notice info">Wähle das Detachement dieser Person. Zusätzliche Aufgebote verknüpfst du später in Schritt 2. «Nicht einplanen» entfernt die Person aus ihren direkten Zuteilungen.</div>`,[{t:'Abbrechen'},{t:'Speichern',primary:true,fn:()=>{
    const status=field('status'),main=field('main'),reason=field('reason');if(!field('person-name'))throw Error('Bitte einen Namen eingeben.');if(status==='excluded'&&!reason)throw Error('Bitte den Entscheid begründen.');if(status==='unreviewed'&&main)throw Error('Für eine Zuteilung zuerst «Einplanen» wählen.');
    const target=p||{id:uid('p'),raw:{},lics:[],pisa:false,milo:false};Object.assign(target,{name:field('person-name'),key:norm(field('person-name')),grad:field('person-grad'),pnr:field('person-pnr'),funktion:field('person-function')});if(!p)S.persons.push(target);
    assignMain(target.id,status==='included'?main:'');target.planning={status,reason};if($('#identityConfirmed')?.checked)delete target.identityReview;UI.personId=target.id;UI.view=returnToPlanning?'groups':'persons';UI.filter='all';UI.query='';$('#globalSearch').value='';afterChange();
  }}]);
}
function detailsDialog(id){
  if(!writable())return;const d=detById(id);if(!d)return;const draft=detailsDraft(d);
  modal('Marschbefehlsangaben · '+d.name,`${d.generatedFrom&&detById(d.generatedFrom)?'<p class="muted">Für das Hauptaufgebot «'+esc(groupName(detById(d.generatedFrom)))+'» mit Zusatz-MB. Noch leere Angaben werden beim ersten Bearbeiten aus dem Hauptaufgebot vorgeschlagen. Vergib einen eigenen EC.</p>':''}<div class="form-grid">${formField('ec','Einrückcode (2 Zeichen)',d.ec,'text','maxlength="2"')}${formField('datum','Einrückdatum',draft.datum||S.service.start,'date')}${formField('von','Einrückzeit',draft.von,'time')}${formField('ort','Einrückort',draft.ort)}${formField('treffpunkt','Treffpunkt',draft.treffpunkt)}${formField('anzug','Anzug',draft.anzug)}${formField('bisDatum','Entlassungsdatum',draft.bisDatum||S.service.end,'date')}${formField('entlassungsort','Entlassungsort',draft.entlassungsort)}<label class="field wide"><span>Bemerkung MB (max. 240 Zeichen)</span><textarea id="field-bem" maxlength="240">${esc(draft.bem)}</textarea></label></div>`,[{t:'Abbrechen'},{t:'Angaben speichern',primary:true,fn:()=>{for(const k of ['ec','datum','von','ort','treffpunkt','anzug','bisDatum','entlassungsort','bem'])d[k]=field(k);afterChange();}}]);
}
function assignDialog(id){if(!writable())return;const d=detById(id);if(!d)return;const selected=new Set(S.assign[id]||[]);
  modal('Personen zuweisen · EC '+(d.ec||'offen'),`<p class="muted">Ausgewählte Personen werden eingeplant und erhalten diese Gruppe als Hauptdetachement. Bestehende direkte Zuteilungen werden ersetzt. Abgewählte Personen bleiben eingeplant, aber ohne diese Zuteilung.</p><input class="search-local" id="assignSearch" aria-label="Personen zum Zuweisen suchen" placeholder="Name, Nummer oder Funktion suchen"><div class="actions" style="margin-bottom:10px"><button class="button small" id="selectMatches">Alle Treffer auswählen</button><button class="button small" id="clearSelection">Auswahl leeren</button><span id="selectionCount" class="muted"></span></div><div class="selection-list" id="assignList"></div>`,[{t:'Abbrechen'},{t:'Zuteilung speichern',primary:true,fn:()=>{const before=[...(S.assign[id]||[])];before.filter(pid=>!selected.has(pid)).forEach(pid=>S.assign[id]=S.assign[id].filter(x=>x!==pid));selected.forEach(pid=>assignMain(pid,id));afterChange();}}]);
  const list=()=>{$('#selectionCount').textContent=selected.size+' ausgewählt';$('#assignList').innerHTML=personenSuche($('#assignSearch').value).map(p=>`<label class="check"><input type="checkbox" data-assign="${esc(p.id)}" ${selected.has(p.id)?'checked':''}><span><b>${esc(p.grad)} ${esc(p.name)}</b><br><small class="muted">${esc(p.pnr||'Nr. fehlt')} · ${esc(participationLabel(p))} · ${esc(directGroups(p.id).map(g=>g.ec).join(', ')||'Keine Gruppe')}</small></span></label>`).join('');$$('[data-assign]').forEach(el=>el.onchange=()=>{if(el.checked)selected.add(el.dataset.assign);else selected.delete(el.dataset.assign);$('#selectionCount').textContent=selected.size+' ausgewählt';});};$('#assignSearch').oninput=list;$('#selectMatches').onclick=()=>{personenSuche($('#assignSearch').value).forEach(p=>selected.add(p.id));list();};$('#clearSelection').onclick=()=>{selected.clear();list();};list();
}
function switchProject(next,lookup=''){
  const proceed=()=>{S=projektNormalisieren(next);UI={...UI,view:S.archive?'persons':'home',query:'',filter:'all',personId:null,groupId:null,pisaId:null,planSelected:new Set(),planQuery:'',planScope:'available',planFilters:null,contacts:null};if(lookup&&personenSuche(lookup).length){UI.query=lookup;UI.personId=personenSuche(lookup)[0]?.id||null;}$('#globalSearch').value=UI.query;afterChange();};
  if(S.persons.length||S.dets.length)modal('Aktuelles Projekt wechseln',`<p>Das aktive Projekt «${esc(S.name)}» wird durch «${esc(next.name)}» ersetzt. Sichere den aktuellen Stand vorher als Datei oder archiviere ihn.</p>`,[{t:'Abbrechen'},{t:'Sichern & wechseln',primary:true,fn:()=>{saveFile();proceed();}},{t:'Ohne Sicherung wechseln',fn:proceed}]);else proceed();
}
function archiveDialog(){if(!writable())return;const pending=!pisaGeprueft();modal('Dienstleistung archivieren',`<p>«${esc(S.name)}» wird als schreibgeschützter Planstand in der lokalen Archivablage gespeichert. Danach öffnet sich die Personensuche.</p>${pending?'<div class="notice"><b>PISA-Abschluss noch nicht bestätigt.</b><br>Dieser Archivstand bleibt als unvollständiger Arbeitsstand erkennbar.</div>':''}<p class="muted">Eine spätere Bearbeitung erzeugt eine separate Arbeitskopie.</p>`,[{t:'Abbrechen'},{t:pending?'Unvollständigen Stand archivieren':'Archivieren',primary:true,fn:archiveCurrent}]);}
function pickFile(accept,callback){const input=$('#fileHidden');input.accept=accept;input.value='';input.onchange=()=>{if(input.files[0])callback(input.files[0]);};input.click();}
function exportXlsx(){const wb=XLSX.utils.book_new();const rows=S.persons.map(p=>({'Grad':p.grad,'Name':p.name,'Versicherten-Nr.':p.pnr||'','Teilnahme':participationLabel(p),'Begründung':p.planning?.reason||'','Hauptdetachement':directGroups(p.id).map(d=>d.ec).join(', '),'Alle EC':detsVon(p.id).map(d=>d.ec).join(', '),'Funktion':fkt(p),'Telefon':p.tel||'','E-Mail':p.mail||'',...Object.fromEntries(Object.entries(p.raw||{}).map(([k,v])=>['Quelle: '+k,v]))}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Personal');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(S.dets.map(d=>({'Gruppe':d.name,...Object.fromEntries(detailWerte(d)),'Zusatz-MB':d.zusatzIds.map(id=>detById(id)?.ec||'?').join(', '),'PISA-Abgleich':erfassungsStatus(d)}))),'Einrückungsdetails');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(S.dets.flatMap(d=>pisaPersonnel(d).map(p=>({'Haupt-EC':d.ec,'Hauptdetachement':d.name,'Zusatz-EC':d.zusatzIds.map(id=>detById(id)?.ec||'EC offen').join(', '),'Grad':p.grad,'Name':p.name,'Versicherten-Nr.':p.pnr||''})))),'PISA-Zuteilungen');XLSX.writeFile(wb,dateiname('xlsx'));}

function mappingDialog(){if(!writable())return;mapsAktualisieren();modal('Kurzformen bearbeiten',`<p class="muted">Diese Anzeigeformen verändern die importierten Originalwerte nicht.</p>${[['fkt','Funktionen'],['lic','Führerausweise']].map(([key,title])=>`<h3>${title}</h3>${Object.entries(S.maps[key]).map(([k,v])=>`<label class="field"><span>${esc(k)}</span><input data-mapkey="${key}" data-original="${esc(k)}" value="${esc(v)}"></label>`).join('')}`).join('')}`, [{t:'Abbrechen'},{t:'Speichern',primary:true,fn:()=>{$$('[data-mapkey]').forEach(el=>S.maps[el.dataset.mapkey][el.dataset.original]=el.value);afterChange();}}]);}
function loadDemo(){if(S.persons.length||S.dets.length){toast('Das Beispiel ist nur in einem leeren Projekt verfügbar.');return;}const demo=leerZustand();demo.name='Beispiel · WK 2027';demo.settings.eigeneEinheit='Demo Kp';demo.service={start:'2027-05-03',end:'2027-05-21',note:'Ausschliesslich fiktive Beispieldaten.'};demo.dets=[neuesDet({id:'demo-wk',name:'WK · Hauptkontingent',ec:'W1',datum:'2027-05-03',von:'08:00',bisDatum:'2027-05-21',ort:'Waffenplatz Beispiel',treffpunkt:'Haupteingang',anzug:'Dienstanzug',entlassungsort:'Waffenplatz Beispiel'}),neuesDet({id:'demo-vor',name:'Vorausdetachement',ec:'V1',datum:'2027-05-02',von:'13:00',bisDatum:'2027-05-21',ort:'Waffenplatz Beispiel'})];demo.persons=['Alex Muster','Kim Beispiel','Robin Demo','Noa Test'].map((name,i)=>({id:'demo-p'+i,name,key:norm(name),grad:['Sdt','Wm','Gfr','Sdt'][i],pnr:'DEMO-00'+(i+1),funktion:['Inf Sdt','Gruppenführer','Motf','Inf Sdt'][i],lics:[],raw:{Hinweis:'Fiktive Testperson'},planning:{status:i<3?'included':'unreviewed',reason:''},pisa:true}));demo.assign={'demo-wk':['demo-p0','demo-p1'],'demo-vor':[]};S=demo;UI.planFilters=null;UI.planQuery='';UI.planSelected=new Set();UI.view='home';afterChange();}
async function handleAction(action,id){
  switch(action){
    case 'contact-edit':contactDialog(id);break;
    case 'contacts-select':visibleContacts().forEach(p=>contactState().selected.add(p.id));refreshContacts();break;
    case 'contacts-clear':contactState().selected.clear();refreshContacts();break;
    case 'service':serviceDialog();break;
    case 'person-new':personDialog();break;case 'person-edit':personDialog(id);break;
    case 'person':UI.personId=id;render();break;case 'open-person':openPerson(id);break;
    case 'filter':UI.view='persons';UI.filter=id;render();break;
    case 'clear-search':UI.query='';UI.filter='all';$('#globalSearch').value='';render();break;
    case 'group':UI.groupId=id;go('groups');break;case 'group-new':groupDialog();break;case 'group-edit':groupDialog(id);break;
    case 'assign':assignDialog(id);break;
    case 'details-edit':detailsDialog(id);break;
    case 'detail-group':UI.groupId=id;go('details');break;
    case 'connect-special':connectionDialog(id);break;
    case 'plan-rest':remainingDialog();break;
    case 'plan-preset':UI.planFilters=null;UI.planQuery='';planningState();UI.planSelected.clear();if(id==='wm')UI.planFilters.grades=['Wm'];if(id==='driver')UI.planFilters.driver='function';if(id==='licence')UI.planFilters.driver='licence';render();break;
    case 'order-edit':orderDialog(id);break;
    case 'planning-import':if(writable())modal('Personenliste laden','<p>Eine Liste genügt zum Start. Wähle die Herkunft deiner Excel- oder CSV-Datei.</p>',[{t:'Abbrechen'},{t:'PISA-Liste wählen',primary:true,fn:()=>pickFile('.xlsx,.xls,.csv',file=>importDialog('pisa',file))},{t:'MILOFFICE-Liste wählen',fn:()=>pickFile('.xlsx,.xls,.csv',file=>importDialog('milo',file))}]);break;
    case 'plan-group':UI.groupId=id;UI.planSelected=new Set();go('groups');break;
    case 'plan-scope':UI.planScope=id;UI.planSelected=new Set();render();break;
    case 'plan-select-all':planningPeople(detById(UI.groupId)).forEach(p=>UI.planSelected.add(p.id));refreshPlanningPeople();break;
    case 'plan-clear':UI.planSelected.clear();refreshPlanningPeople();break;
    case 'plan-assign':if(writable()){UI.planSelected.forEach(pid=>assignMain(pid,UI.groupId));UI.planSelected.clear();afterChange();}break;
    case 'plan-remove':if(writable()){S.assign[UI.groupId]=(S.assign[UI.groupId]||[]).filter(pid=>!UI.planSelected.has(pid));UI.planSelected.clear();afterChange();}break;
    case 'group-delete':if(!writable())break;modal('Einrückungsgruppe löschen',`<p>Die Gruppe «${esc(detById(id).name)}» und ihre Verknüpfungen werden entfernt. Personen bleiben erhalten und müssen gegebenenfalls neu zugeteilt werden.</p>`,[{t:'Abbrechen'},{t:'Gruppe löschen',danger:true,fn:()=>{S.dets=S.dets.filter(d=>d.id!==id);S.dets.forEach(d=>d.zusatzIds=d.zusatzIds.filter(x=>x!==id));delete S.assign[id];delete S.pisa.entered[id];afterChange();}}]);break;
    case 'pisa-group':UI.pisaId=id;UI.pisaStep='details';go('pisa');break;
    case 'pisa-step':UI.pisaStep=id;render();break;
    case 'confirm-group':if(!writable())break;{const d=detById(id);if(!d||pisaFehler(d).length||!groupPeople(d).length)break;S.pisa.entered[id]={at:new Date().toISOString(),signature:detSignatur(d)};afterChange();toast('Abgleich dieses EC festgehalten.');}break;
    case 'verify':if(!writable()||!isReady())break;S.pisa.verified={at:new Date().toISOString(),signature:planSignatur()};afterChange();toast('Manuellen PISA-Abschluss festgehalten.');break;
    case 'copy-details':await copyText(detailWerte(detById(id)).map(([k,v])=>k+': '+v).join('\n'));break;
    case 'copy-persons':await copyText(pisaPersonnelText(detById(id)));break;
    case 'save-file':saveFile();break;case 'export-html':exportBundle();break;case 'export-xlsx':exportXlsx();break;case 'export-contacts':exportContacts();break;
    case 'archive':archiveDialog();break;case 'resume':resumeCurrent();break;
    case 'new-project':switchProject(leerZustand());break;
    case 'open-archive':{const found=archiveLibrary().find(x=>x.archive.id===id);if(found)switchProject(found,UI.archiveQuery);}break;
    case 'load-file':pickFile('.json',async file=>{try{const next=projektNormalisieren(JSON.parse(await file.text()));switchProject(next);}catch(e){toast(e.message);}});break;
    case 'import':if(writable())pickFile('.xlsx,.xls,.csv',file=>importDialog(id,file));break;
    case 'mappings':mappingDialog();break;case 'demo':loadDemo();break;case 'print':window.print();break;
  }
}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('In die Zwischenablage kopiert.');}catch(e){modal('Angaben kopieren',`<p class="muted">Markiere die Angaben und kopiere sie mit Ctrl+C.</p><textarea readonly style="min-height:250px" aria-label="Angaben zum Kopieren">${esc(text)}</textarea>`);}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){e.preventDefault();go(nav.dataset.nav);return;}const action=e.target.closest('[data-action]');if(action)handleAction(action.dataset.action,action.dataset.id).catch(err=>toast(err.message));});
document.addEventListener('change',e=>{if(e.target.matches('[data-contact-person]')){const selected=contactState().selected;if(e.target.checked)selected.add(e.target.dataset.contactPerson);else selected.delete(e.target.dataset.contactPerson);refreshContacts();}if(e.target.matches('[data-contact-filter]')){contactState()[e.target.dataset.contactFilter]=e.target.value;refreshContacts();}if(e.target.matches('[data-contact-option]')){contactState()[e.target.dataset.contactOption]=e.target.checked;refreshContacts();}if(e.target.matches('[data-plan-filter]')){planningState();UI.planFilters[e.target.dataset.planFilter]=e.target.multiple?Array.from(e.target.selectedOptions,o=>o.value):e.target.value;UI.planSelected.clear();refreshPlanningPeople();}if(e.target.matches('[data-plan-person]')){planningState();if(e.target.checked)UI.planSelected.add(e.target.dataset.planPerson);else UI.planSelected.delete(e.target.dataset.planPerson);$('#planSelection').innerHTML=planningSelectionHtml(detById(UI.groupId));}});
document.addEventListener('input',e=>{if(e.target.id==='contactSearch'){contactState().query=e.target.value;refreshContacts();}if(e.target.id==='contactLabel'){contactState().label=e.target.value;refreshContacts();}if(e.target.id==='planSearch'){UI.planQuery=e.target.value;UI.planSelected.clear();refreshPlanningPeople();}if(e.target.id==='archiveSearch'){UI.archiveQuery=e.target.value;render();$('#archiveSearch').focus();}});
$('#closeDialog').onclick=()=>$('#dlg').close();
$('#globalSearch').oninput=e=>{UI.query=e.target.value;UI.view='persons';UI.filter='all';render();};
$('#globalSearch').onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){const list=visiblePeople();if(!list.length)return;e.preventDefault();const index=list.findIndex(p=>p.id===UI.personId);UI.personId=list[Math.max(0,Math.min(list.length-1,index+(e.key==='ArrowDown'?1:-1)))].id;UI.view='persons';render();}else if(e.key==='Escape'){UI.query='';e.target.value='';render();}};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&!$('#dlg').open){e.preventDefault();$('#globalSearch').focus();}});
window.addEventListener('DOMContentLoaded',()=>{
  TEMPLATE='<!DOCTYPE html>\n'+document.documentElement.outerHTML;
  if(window.__BOOTDATA){try{S=projektNormalisieren(window.__BOOTDATA);UI.view=S.archive?'persons':'home';setState('Dateiprojekt geöffnet · explizit sichern');}catch(e){toast(e.message);laden();}}else{laden();if(istArchiv())UI.view='persons';}
  render();
});
