// Planning comes before the PISA data-entry workflow. Draft groups need only a name.
function workflowSteps(active){return `<nav class="workflow" aria-label="Planungsablauf">${[['groups','1','Detachemente bilden'],['orders','2','Marschbefehle zuordnen'],['details','3','Angaben ergänzen'],['pisa','4','In PISA übernehmen']].map(([key,n,label])=>`<button data-nav="${key}" class="${active===key?'active':''}" ${active===key?'aria-current="step"':''}><span>${n}</span>${label}</button>`).join('')}</nav>`;}
function groupName(d){return d?.name||'Unbenanntes Detachement';}
function planningState(){UI.planSelected ||= new Set();UI.planQuery ||= '';UI.planScope ||= 'available';UI.planFilters ||= {grades:[],functions:[],licences:[],units:[],platoons:[],driver:'',source:''};}
function gradeKey(value){const key=norm(value);return ({wachtmeister:'Wm',oberwachtmeister:'Obwm',korporal:'Kpl',soldat:'Sdt',gefreiter:'Gfr',obergefreiter:'Obgfr',leutnant:'Lt',oberleutnant:'Oblt',hauptmann:'Hptm',feldweibel:'Fw',hauptfeldweibel:'Hptfw',fourier:'Four'})[key]||GRADE_ORDER.find(g=>norm(g)===key)||String(value||'').trim();}
function matchesPlanningFilters(p){const f=UI.planFilters;return (!f.grades.length||f.grades.includes(gradeKey(p.grad)))&&(!f.functions.length||f.functions.includes(String(p.funktion||'')))&&(!f.licences.length||f.licences.some(code=>(p.lics||[]).some(raw=>code.startsWith('raw:')?raw===code.slice(4):licCode(raw)===code)))&&(!f.units.length||f.units.includes(String(p.einteilung||'')))&&(!f.platoons.length||f.platoons.includes(String(p.zug||'')))&&(!f.driver||(f.driver==='function'?istFahrer(p):hatAusweis(p)))&&(!f.source||(f.source==='both'?p.pisa&&p.milo:p[f.source]));}
function planningPeople(d){planningState();return personenSuche(UI.planQuery).filter(p=>(UI.planScope==='current'?(S.assign[d.id]||[]).includes(p.id):UI.planScope==='all'||!zugeteilt(p.id)&&participation(p)!=='excluded')&&matchesPlanningFilters(p));}
function planningFiltersHtml(){planningState();const f=UI.planFilters;const values=key=>[...new Set(S.persons.map(p=>String(p[key]||'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de-CH'));const multi=(key,label,options)=>`<label class="field"><span>${label} · Mehrfachauswahl</span><select multiple size="3" data-plan-filter="${key}" aria-label="${label} filtern">${options.map(([v,t])=>`<option value="${esc(v)}" ${f[key].includes(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;const licences=new Map();S.persons.forEach(p=>(p.lics||[]).forEach(raw=>{if(kurzKategorie(raw))licences.set(licCode(raw)||'raw:'+raw,(licCode(raw)?licCode(raw)+' · ':'')+kurzKategorie(raw));}));return `<div class="actions filter-presets">${btn('Wachtmeister','plan-preset','wm')}${btn('Fahrer gemäss Funktion','plan-preset','driver')}${btn('Mit Fahrausweis','plan-preset','licence')}${btn('Filter zurücksetzen','plan-preset','reset')}</div><details class="planning-filters" ${Object.values(f).some(v=>v.length)?'open':''}><summary>Weitere Filter: Grad, Funktion, Fahrausweis, Zug und Quelle</summary><div class="filter-grid">${multi('grades','Grad',[...new Set(S.persons.map(p=>gradeKey(p.grad)).filter(Boolean))].sort((a,b)=>gradIdx(a)-gradIdx(b)).map(x=>[x,x]))}${multi('functions','Funktion',values('funktion').map(x=>[x,kurzFunktion(x)||x]))}${multi('licences','Führerausweis',[...licences])}${multi('platoons','Zug / Element',values('zug').map(x=>[x,x]))}${multi('units','Einheit',values('einteilung').map(x=>[x,x]))}<div><label class="field"><span>Fahrer-Auswahl</span><select data-plan-filter="driver" aria-label="Fahrer filtern">${[['','Alle'],['function','Fahrer gemäss Funktion'],['licence','Mit militärischem Fahrausweis']].map(([v,t])=>`<option value="${v}" ${f.driver===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span>Datenquelle</span><select data-plan-filter="source" aria-label="Datenquelle filtern">${[['','Alle Quellen'],['pisa','In PISA'],['milo','In MILOFFICE'],['both','In beiden Quellen']].map(([v,t])=>`<option value="${v}" ${f.source===v?'selected':''}>${t}</option>`).join('')}</select></label></div></div><small class="muted">Mehrere Werte je Feld gelten als ODER. Unterschiedliche Felder werden mit UND kombiniert. Mehrfachauswahl mit Ctrl/Cmd. Filteränderungen heben die bisherige Auswahl auf.</small></details>`;}
function viewGroups(){
  planningState();const d=detById(UI.groupId)||S.dets[0];if(d)UI.groupId=d.id;
  const headingText=!S.dets.length?'Welche Detachemente brauchst du?':'Wer kommt in welches Detachement?';
  const parents=d?S.dets.filter(g=>g.zusatzIds.includes(d.id)):[];
  const head=workflowSteps('groups')+heading(headingText,'Zuerst Spezialpersonen auswählen und zuteilen, dann die übrigen Personen auf die Hauptdetachemente verteilen. PISA-Details kommen später.',istArchiv()?'':btn('+ Detachement','group-new'),'1 · DETACHEMENTE BILDEN');
  if(!S.persons.length&&!istArchiv())return workflowSteps('groups')+heading('Zuerst die Personenliste laden.','PISA, MILOFFICE oder beide. Danach bildest du Spezialdetachemente und verteilst die übrigen Personen.','','BESTAND ÜBERNEHMEN')+empty('Welche Liste hast du?','Excel oder CSV genügt. Deine bestehenden Detachemente bleiben erhalten.',btn('PISA-Liste laden','import','pisa',true)+btn('MILOFFICE-Liste laden','import','milo')+btn('Projektdatei öffnen','load-file'))+`<div class="actions">${btn('Detachemente vorab anlegen','group-new')}${!S.dets.length?btn('Beispiel ansehen','demo'):''}</div>`;
  if(!d)return head+`<section class="panel start-planning"><span class="section-label">HIER BEGINNST DU</span><h2>Gib deinen Detachementen einen Namen.</h2><p class="muted">Zum Beispiel «WK Gros», «WK Fahrer» oder «Fahrerrepetitorium». Für den Anfang reicht der Name.</p><div class="actions">${istArchiv()?'':btn('Detachemente anlegen','group-new','',true)}${btn('Bestehendes Projekt öffnen','load-file')}</div><div class="start-next"><b>${S.persons.length} Personen sind geladen.</b><p class="muted">Besetze zuerst die Spezialdetachemente. Anschliessend verteilst du die noch freien Personen auf die Hauptdetachemente.</p>${!S.persons.length&&!istArchiv()?btn('Beispiel ansehen','demo'):''}</div></section>`;
  return head+`<div class="planning-board"><aside class="panel"><div class="panel-head"><h3>Deine Detachemente</h3><span class="muted">${S.dets.length}</span></div>${S.dets.map(g=>`<button class="list-item ${g.id===d.id?'active':''}" data-action="plan-group" data-id="${esc(g.id)}"><span class="grow"><b>${esc(g.name)}</b><small>${groupPeople(g).length} Personen${S.dets.some(x=>x.zusatzIds.includes(g.id))?' · mit Zusatz-Zuteilungen':''}</small></span><span>→</span></button>`).join('')}<div class="panel-body">${istArchiv()?'':btn('+ Detachement','group-new')}</div></aside><section class="panel"><div class="panel-head"><div><span class="section-label">AUSGEWÄHLTES DETACHEMENT</span><h2>${esc(d.name)}</h2></div><div class="actions">${istArchiv()?'':btn('Umbenennen','group-edit',d.id)+btn('Entfernen','group-delete',d.id)}</div></div>${parents.length&&!(S.assign[d.id]||[]).length?`<div class="panel-body"><div class="notice info"><b>Die Personen kommen über das Hauptdetachement.</b><br>Dieses Detachement ist als Zusatzmarschbefehl verknüpft. Du musst die Personen hier nicht nochmals zuteilen.</div>${parents.map(g=>btn('Personen bei «'+esc(g.name)+'» verteilen','plan-group',g.id)).join(' ')}</div>`:!S.persons.length?`<div class="empty"><h2>Jetzt die Personen dazunehmen.</h2><p>Lade deine Liste. Anschliessend wählst du Personen aus und teilst sie diesem Detachement zu.</p><div class="actions">${istArchiv()?'':btn('Personenliste laden','planning-import','',true)+btn('Person einzeln erfassen','person-new')}</div></div>`:`<div class="panel-body"><div class="actions" style="justify-content:space-between;margin-bottom:16px"><div class="filters" style="margin:0">${[['available','Noch zu verteilen'],['current','In diesem Detachement'],['all','Alle Personen']].map(([key,t])=>`<button class="filter ${UI.planScope===key?'active':''}" data-action="plan-scope" data-id="${key}">${t}</button>`).join('')}</div>${istArchiv()?'':btn('Liste laden','planning-import')}</div><input id="planSearch" type="search" aria-label="Personen zum Verteilen suchen" placeholder="Name, Funktion, Zug oder Versicherten-Nr. suchen…" value="${esc(UI.planQuery)}">${planningFiltersHtml()}<div id="planPeople">${planningPeopleHtml(d)}</div><div id="planSelection">${planningSelectionHtml(d)}</div></div>`}<div class="planning-summary"><b>${groupPeople(d).length} Personen in ${esc(d.name)}</b><p class="muted">${groupPeople(d).map(p=>esc(p.name)).join(' · ')||'Noch niemand zugeteilt.'}</p>${d.zusatzIds.length?`<p class="muted">Zusätzlich verknüpft: ${d.zusatzIds.map(id=>esc(groupName(detById(id)))).join(', ')}. ${navbtn('Verknüpfung ansehen','orders')}</p>`:''}</div></section></div><div class="next-step"><div><b>Die Detachemente stehen?</b><p class="muted">Als Nächstes klären wir, wer nur einen Marschbefehl und wer zusätzliche Marschbefehle erhält.</p></div>${navbtn('Weiter: Marschbefehle zuordnen','orders',true)}</div>`;
}
function planningPeopleHtml(d){const list=planningPeople(d);return `<div class="actions" style="margin:15px 0"><small class="muted">${list.length} Personen</small>${!istArchiv()&&list.length?btn('Alle Treffer auswählen','plan-select-all'):''}</div><div class="plan-person-list">${list.map(p=>`<label class="plan-person"><input type="checkbox" data-plan-person="${esc(p.id)}" ${UI.planSelected.has(p.id)?'checked':''} ${istArchiv()?'disabled':''}><span class="grow"><b>${esc(p.grad)} ${esc(p.name)}</b><small>${esc([fkt(p),p.zug].filter(Boolean).join(' · ')||p.pnr||'Keine weiteren Angaben')}</small></span><span class="muted">${esc(directGroups(p.id).map(g=>g.name).join(', ')||(participation(p)==='excluded'?'Nicht eingeplant':'Noch frei'))}</span></label>`).join('')||`<div class="empty" style="padding:25px"><p>${UI.planQuery||Object.values(UI.planFilters).some(v=>v.length)?'Keine passenden Personen. Filter anpassen oder zurücksetzen.':UI.planScope==='available'?'Alle verfügbaren Personen sind verteilt. Wähle «Alle Personen», um jemanden zu verschieben.':'Hier sind noch keine Personen.'}</p></div>`}</div>`;}
function planningSelectionHtml(d){const n=UI.planSelected.size;return istArchiv()?'':`<div class="assignment-bar"><span>${n?n+' ausgewählt':'Personen links ankreuzen'}</span><div class="actions">${n?btn('Auswahl aufheben','plan-clear'):''}${UI.planScope==='available'?btn('Alle übrigen hier zuteilen','plan-rest'):''}<button class="button primary" data-action="plan-assign" ${n?'':'disabled'}>Zu «${esc(d.name)}» zuteilen</button>${UI.planScope==='current'&&n?btn('Aus Detachement nehmen','plan-remove'):''}</div></div><small class="muted">Zuteilen bestätigt die Einplanung. Bei bereits zugeteilten Personen wird das bisherige Detachement ersetzt.</small>`;}
function refreshPlanningPeople(){const d=detById(UI.groupId);if(!d)return;$('#planPeople').innerHTML=planningPeopleHtml(d);$('#planSelection').innerHTML=planningSelectionHtml(d);}
function createPlanningGroups(names){if(istArchiv())return[];const clean=[...new Set(names.map(n=>String(n).trim()).filter(Boolean))];if(!clean.length)throw Error('Bitte mindestens einen Namen eingeben.');const groups=clean.map(name=>neuesDet({name}));groups.forEach(d=>{S.dets.push(d);S.assign[d.id]=[];});return groups;}
function groupDialog(id){
  if(!writable())return;const d=detById(id);
  modal(d?'Detachement umbenennen':'Detachemente anlegen',d?formField('group-name','Name des Detachements',d.name):`<p class="muted">Ein Name pro Zeile. Du kannst später jederzeit weitere Detachemente hinzufügen.</p><label class="field"><span>Namen der Detachemente</span><textarea id="field-group-names" rows="5" placeholder="WK Gros\nWK Fahrer\nFahrerrepetitorium"></textarea></label><p class="muted">Datum, EC, Ort und die übrigen Marschbefehlsangaben kommen erst in Schritt 3.</p>`,[{t:'Abbrechen'},{t:d?'Speichern':'Detachemente anlegen',primary:true,fn:()=>{if(d){if(!field('group-name'))throw Error('Bitte einen Namen eingeben.');d.name=field('group-name');}else{const added=createPlanningGroups(field('group-names').split('\n'));UI.groupId=added[0].id;}UI.view='groups';afterChange();}}]);
}
function mbExplanation(){return `<details class="panel mb-explainer" open><summary>Hauptmarschbefehl und Zusatzmarschbefehl – was bedeutet das?</summary><div class="panel-body"><p>Der <b>Hauptmarschbefehl</b> ist das führende Aufgebot. Bei verknüpften Aufgeboten ist das der WK-Marschbefehl. Ein <b>Zusatzmarschbefehl</b> ist ein weiteres, damit verbundenes Aufgebot für dieselben Personen – keine Beilage.</p><div class="order-example"><div><small>FREITAG</small><b>Fahrerrepetitorium</b>${badge('Zusatzmarschbefehl','neutral')}</div><span aria-hidden="true">→</span><div><small>AB MONTAG</small><b>WK</b>${badge('Hauptmarschbefehl')}</div></div><p class="muted">Beispiel aus der PAT: Die Fahrer erhalten das Repetitorium zusätzlich zum WK. <b>«Haupt» bedeutet also nicht «zuerst».</b> Wer nur zum WK kommt, braucht diese Zusatzverknüpfung nicht.</p><details><summary>Fraktionen und KVK/WK-Sonderfälle</summary><p class="muted">Bei ausdrücklich befohlenen Fraktionen ist der letzte Dienstabschnitt der Hauptmarschbefehl; frühere Abschnitte werden als Zusatz-MB verknüpft. Auf Kp-Stufe zuerst mit KF absprechen. Für KVK und WK enthält die PAT widersprüchliche Aussagen zur MB-Anzahl: deshalb keine automatische Zusammenlegung oder Verknüpfung.</p><small class="muted">PAT S. 85–89, 93–98 · Oracle MB-001/002, FRACTION-002, CONFLICT-001</small></details></div></details>`;}
function orderPreview(d){const people=(S.assign[d.id]||[]).map(pById).filter(Boolean),parents=S.dets.filter(g=>g.zusatzIds.includes(d.id));
  if(!people.length)return `<div class="order-preview">${parents.length?`<div class="order-extra"><small>Zusatzmarschbefehl</small><b>${esc(d.name)}</b></div><p>Zusätzliches Aufgebot für ${groupPeople(d).length} ${groupPeople(d).length===1?'Person':'Personen'} aus ${parents.map(g=>esc(g.name)).join(', ')}.</p><small class="muted">${groupPeople(d).map(p=>esc(p.name)).join(' · ')}</small><p class="muted">Die Personen werden über ihre Hauptdetachemente übernommen. Hier ist keine zweite Zuteilung nötig.</p>`:'<p class="muted">Noch keine Personen und keine Zusatzverknüpfung. Dieses Detachement kannst du einer Gruppe als zusätzlichen Marschbefehl zuordnen oder in Schritt 1 mit Personen belegen.</p>'}</div>`;
  return `<div class="order-preview"><span class="section-label">SO ERHALTEN DIESE PERSONEN IHRE MARSCHBEFEHLE</span><h3>${people.length} ${people.length===1?'Person':'Personen'} · ${esc(d.name)}</h3><div class="order-route"><div class="order-main"><small>Hauptmarschbefehl</small><b>${esc(d.name)}</b></div>${d.zusatzIds.map(id=>`<span class="order-plus">+</span><div class="order-extra"><small>Zusatzmarschbefehl</small><b>${esc(groupName(detById(id)))}</b></div>`).join('')}</div><p class="muted">${d.zusatzIds.length?'Jede direkt zugeteilte Person erhält den Hauptmarschbefehl und die aufgeführten Zusatzmarschbefehle.':'Aktuell ist für diese Personen nur dieses Aufgebot vorgesehen.'}</p><small class="muted">${people.map(p=>esc(p.name)).join(' · ')||'Noch keine Personen zugeteilt.'}</small></div>`;}
function viewOrders(){
  const head=workflowSteps('orders')+heading('Wer braucht mehr als einen Marschbefehl?','Verbinde jedes besetzte Spezialdetachement mit seinem Hauptaufgebot. Die App bereitet daraus die Zuteilung für PISA vor.','','2 · MARSCHBEFEHLE ZUORDNEN');
  if(!S.dets.length)return head+empty('Zuerst Detachemente bilden','Für die Zuordnung verwenden wir deine Gruppen und deren Personen.',navbtn('Detachemente anlegen','groups',true));
  return head+mbExplanation()+`<div class="notice info"><b>Spezialpersonen bereits verteilt? Jetzt nur noch verbinden.</b><br>Beim Spezialdetachement «Als Spezialdetachement verbinden» wählen und das Hauptaufgebot angeben. Die App erstellt automatisch das Hauptdetachement mit Zusatz-MB für diese Personen. Der reine Zusatz erhält keine direkte Personenzuteilung. ${navbtn('Personen verteilen','groups')}</div>${S.dets.map(d=>`<section class="panel"><div class="panel-head"><h2>${esc(d.name)}</h2>${istArchiv()?'':orderActions(d)}</div>${orderPreview(d)}${(S.assign[d.id]||[]).length&&S.dets.some(g=>g.zusatzIds.includes(d.id))?`<div class="panel-body muted">Dieses Detachement ist ausserdem als Zusatz verknüpft mit: ${S.dets.filter(g=>g.zusatzIds.includes(d.id)).map(g=>esc(g.name)).join(', ')}.</div>`:''}</section>`).join('')}<div class="next-step"><div><b>Für jede Person ist klar, welche Aufgebote sie erhält?</b><p class="muted">Jetzt erst die Angaben für die Marschbefehle ergänzen.</p></div>${navbtn('Weiter: Angaben ergänzen','details',true)}</div>`;
}
function setAdditionalOrders(id,extras){if(istArchiv())return;const d=detById(id);if(!d)throw Error('Detachement nicht gefunden.');const ids=[...new Set(extras)];if(ids.length>5)throw Error('Höchstens fünf Zusatzmarschbefehle möglich.');if(ids.some(x=>x===id||!detById(x)||detById(x).zusatzIds.length)||ids.length&&S.dets.some(g=>g.zusatzIds.includes(id)))throw Error('Eine Zusatzverknüpfung darf nicht auf sich selbst zeigen oder weitere Zusatzverknüpfungen enthalten.');d.zusatzIds=ids;}
function orderDialog(id){
  if(!writable())return;const d=detById(id);const others=S.dets.filter(g=>g.id!==id);
  modal('Weitere Aufgebote für '+d.name,`<div class="notice info"><b>Hauptmarschbefehl: ${esc(d.name)}</b><br>Alle ${(S.assign[id]||[]).length} direkt zugeteilten Personen erhalten die ausgewählten Aufgebote zusätzlich. Ein Zusatzmarschbefehl ist keine PDF-Beilage.</div><p>Zu welchen weiteren Detachementen sollen diese Personen ebenfalls aufgeboten werden?</p>${others.map(g=>`<label class="check"><input type="checkbox" data-order-extra="${esc(g.id)}" ${d.zusatzIds.includes(g.id)?'checked':''}><span><b>${esc(g.name)}</b><br><small class="muted">${(S.assign[g.id]||[]).length?'Die dort bereits direkt zugeteilten Personen bleiben unverändert.':'Personen aus dem Hauptdetachement erscheinen hier automatisch mit.'}</small></span></label>`).join('')||'<p class="muted">Lege zuerst das zusätzliche Detachement in Schritt 1 an.</p>'}<div id="orderImpact"></div>`,[{t:'Abbrechen'},{t:'Verknüpfung speichern',primary:true,fn:()=>{setAdditionalOrders(id,$$('[data-order-extra]:checked').map(el=>el.dataset.orderExtra));afterChange();}}]);
  const impact=()=>{const selected=$$('[data-order-extra]:checked').map(el=>groupName(detById(el.dataset.orderExtra)));$('#orderImpact').innerHTML=`<div class="order-impact"><b>Ergebnis pro Person</b><p>${esc(d.name)} (Haupt)${selected.map(n=>' + '+esc(n)+' (Zusatz)').join('')}</p><small>${1+selected.length} Marschbefehl${selected.length?'e':''} pro Person · ${selected.length} von höchstens 5 Zusatz-MB</small></div>`;};$$('[data-order-extra]').forEach(el=>el.onchange=impact);impact();
}
function viewDetails(){
  const head=workflowSteps('details')+heading('Jetzt die Angaben für die Marschbefehle.','Die Gruppen und Zuteilungen bleiben erhalten. Ergänze hier je Detachement die Angaben, die du anschliessend in PISA erfasst.',istArchiv()?'':btn('Dienstleistung benennen','service'),'3 · ANGABEN ERGÄNZEN');
  if(!S.dets.length)return head+empty('Noch keine Detachemente','Beginne mit den Gruppen und ihren Personen.',navbtn('Zur Planung','groups',true));
  const d=detById(UI.groupId)||S.dets[0];UI.groupId=d.id;const issues=pisaFehler(d);
  return head+`<div class="workspace"><section class="panel">${S.dets.map(g=>`<button class="list-item ${g.id===d.id?'active':''}" data-action="detail-group" data-id="${esc(g.id)}"><span class="grow"><b>${esc(g.name)}</b><small>${pisaFehler(g).length?'Angaben noch ergänzen':'Angaben vollständig'}</small></span>${badge(pisaFehler(g).length?'Offen':'✓',pisaFehler(g).length?'neutral':'')}</button>`).join('')}</section><section class="panel"><div class="panel-head"><h2>${esc(d.name)}</h2>${istArchiv()?'':btn('Angaben bearbeiten','details-edit',d.id,true)}</div><dl class="detail-grid">${detailWerte(d).map(([k,v])=>detail(k,v,k==='Bemerkung MB')).join('')}</dl>${issues.length?`<div class="notice" style="margin:0 24px 24px"><b>Noch zu ergänzen / prüfen</b><ul>${issues.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`:''}</section></div><div class="next-step"><div><b>Die Angaben sind bereit?</b><p class="muted">Übernimm sie in PISA und halte den Abgleich fest.</p></div>${navbtn('Weiter: In PISA übernehmen','pisa',true)}</div>`;
}

function orderActions(d){const parents=S.dets.filter(g=>g.zusatzIds.includes(d.id));return parents.length&&!(S.assign[d.id]||[]).length?parents.map(g=>btn('Bei «'+esc(g.name)+'» ändern','order-edit',g.id)).join(' '):`<div class="actions">${!parents.length&&!d.zusatzIds.length&&(S.assign[d.id]||[]).length?btn('Als Spezialdetachement verbinden','connect-special',d.id,true):''}${d.zusatzIds.length?btn('Zusatz-MB ändern','order-edit',d.id):`<details class="direct-order"><summary>Andere Zuordnung</summary>${btn('Zusatz-MB direkt wählen','order-edit',d.id)}</details>`}</div>`;}

function remainingPeople(){return S.persons.filter(p=>!zugeteilt(p.id)&&participation(p)!=='excluded');}
function assignRemaining(id){if(istArchiv())return;const d=detById(id);if(!d||S.dets.some(g=>g.zusatzIds.includes(id)))throw Error('Bitte ein Hauptdetachement wählen.');const ids=remainingPeople().map(p=>p.id);ids.forEach(pid=>assignMain(pid,id));return ids.length;}
function remainingDialog(){if(!writable())return;const d=detById(UI.groupId),people=remainingPeople();modal('Übrige Personen zuteilen',`<p><b>${people.length} noch freie Personen</b> werden «${esc(d.name)}» zugeteilt. Das umfasst alle noch freien Personen, unabhängig von den aktiven Suchfiltern.</p><p class="muted">Bereits zugeteilte und ausdrücklich nicht eingeplante Personen bleiben unverändert.</p><div class="selection-list">${people.map(p=>`<p>${esc(p.grad)} ${esc(p.name)}</p>`).join('')}</div>`,[{t:'Abbrechen'},{t:people.length+' Personen zuteilen',primary:true,fn:()=>{assignRemaining(d.id);UI.planSelected.clear();afterChange();}}]);}
function specialConnectionPlan(specialId,mainId){
  const special=detById(specialId),main=detById(mainId);
  if(!special||!main||specialId===mainId)throw Error('Spezial- und Hauptdetachement müssen verschieden sein.');
  if(special.zusatzIds.length||main.zusatzIds.length||S.dets.some(g=>g.zusatzIds.includes(specialId)||g.zusatzIds.includes(mainId)))throw Error('Bitte zwei noch nicht verknüpfte Detachemente wählen. Bestehende Verknüpfungen können separat geändert werden.');
  const ids=[...new Set(S.assign[specialId]||[])];
  if(!ids.length)throw Error('Teile dem Spezialdetachement zuerst Personen zu.');
  if(ids.some(id=>!pById(id)||directGroups(id).length!==1||participation(pById(id))==='excluded'))throw Error('Bitte zuerst fehlende Personen, Mehrfachzuteilungen oder ausgeschlossene Personen im Spezialdetachement klären.');
  return {special,main,ids,name:main.name+' · '+special.name};
}
function connectSpecial(specialId,mainId){
  if(istArchiv())return;
  const {special,main,ids,name}=specialConnectionPlan(specialId,mainId);
  const group=neuesDet({...JSON.parse(JSON.stringify(main)),id:uid('d'),name,ec:'',zusatzIds:[special.id],generatedFrom:main.id});
  S.dets.push(group);S.assign[group.id]=[];ids.forEach(id=>assignMain(id,group.id));return group;
}
function connectionDialog(id){
  if(!writable())return;const special=detById(id),mains=S.dets.filter(d=>d.id!==id&&!d.zusatzIds.length&&!S.dets.some(g=>g.zusatzIds.includes(d.id)));
  modal('Spezialdetachement verbinden',`<p><b>${esc(special.name)}</b> wird zum Zusatzmarschbefehl. Zu welchem Hauptaufgebot gehören seine ${(S.assign[id]||[]).length} ${S.assign[id]?.length===1?'Person':'Personen'} anschliessend?</p><label class="field"><span>Hauptdetachement</span><select id="connectionMain" aria-label="Hauptdetachement"><option value="">Bitte wählen</option>${mains.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><div id="connectionPreview"><p class="muted">Wähle beispielsweise das WK-Hauptdetachement.</p></div>`,[{t:'Abbrechen'},{t:'Verbindung erstellen',primary:true,fn:()=>{connectSpecial(id,$('#connectionMain').value);afterChange();}}]);
  $('#connectionMain').onchange=()=>{try{const plan=specialConnectionPlan(id,$('#connectionMain').value);$('#connectionPreview').innerHTML=`<div class="notice info"><b>Das entsteht automatisch:</b><ul><li>«${esc(special.name)}»: Zusatz-MB, keine direkt zugeteilten Personen.</li><li>«${esc(plan.name)}»: neues Hauptdetachement mit ${plan.ids.length} ${plan.ids.length===1?'Person':'Personen'} und dem Zusatz «${esc(special.name)}».</li><li>«${esc(plan.main.name)}»: seine bisherigen Personen behalten nur ihr Hauptaufgebot.</li></ul><p>Die Hauptangaben werden kopiert. Den eigenen EC für das neue Hauptdetachement ergänzt du in Schritt 3.</p></div><p>${plan.ids.map(pid=>esc(pById(pid).name)).join(' · ')}</p>`;}catch(e){$('#connectionPreview').textContent=e.message;}};
}
function pisaPersonnel(d){return S.persons.filter(p=>(S.assign[d.id]||[]).includes(p.id));}
function pisaPersonnelText(d){const people=pisaPersonnel(d);return people.length?people.map(p=>[p.grad,p.name,p.pnr||'',d.ec,d.zusatzIds.map(id=>detById(id)?.ec||'EC offen').join(', ')].join('\t')).join('\n'):'Keine Personen bei diesem EC hinzufügen. Zusatz-MB beim zugehörigen Hauptdetachement verknüpfen.';}
function pisaPersonnelHtml(d){
  const people=pisaPersonnel(d),parents=S.dets.filter(g=>g.zusatzIds.includes(d.id));
  if(!people.length)return `<div class="notice info"><b>0 Personen hier hinzufügen${parents.length?' · reiner Zusatzmarschbefehl':''}.</b><p>${parents.length?'Die Personen werden beim verknüpften Hauptdetachement erfasst. Hier nur die Detailangaben MB erfassen.':'Diese Gruppe ist noch nicht besetzt oder verknüpft.'}</p></div>${parents.map(g=>`<p>Hauptdetachement: <b>${esc(g.ec||'EC offen')} · ${esc(g.name)}</b> · ${pisaPersonnel(g).length} ${pisaPersonnel(g).length===1?'Person':'Personen'} ${btn('In PISA übernehmen','pisa-group',g.id)}</p>`).join('')}`;
  return `<h3>${people.length} ${people.length===1?'Person':'Personen'} bei diesem Hauptdetachement hinzufügen</h3><ol class="pisa-entry-steps"><li>In PISA <b>Detachemente</b> öffnen und Haupt-EC <b>${esc(d.ec||'EC noch ergänzen')}</b> wählen.</li><li>${d.zusatzIds.length?'Über die Lupe folgende Zusatz-MB wählen: <b>'+d.zusatzIds.map(id=>esc(detById(id)?.ec||'EC offen')+' · '+esc(groupName(detById(id)))).join(', ')+'</b>.':'Keinen Zusatz-MB auswählen.'}</li><li><b>Personal hinzufügen</b>: die unten aufgeführten Personen auswählen und mit <b>OK</b> bestätigen.</li><li><b>Speichern</b>.</li></ol><table><thead><tr><th>Grad</th><th>Person</th><th>Versicherten-Nr.</th></tr></thead><tbody>${people.map(p=>`<tr><td>${esc(p.grad)}</td><td>${esc(p.name)}</td><td>${esc(p.pnr||'—')}</td></tr>`).join('')}</tbody></table><div class="actions" style="margin-top:20px">${btn('Personalliste kopieren','copy-persons',d.id)}${btn('Zuteilungen ansehen','group',d.id)}</div>`;
}

function detailsDraft(d){
  const fields=['datum','von','ort','treffpunkt','anzug','bisDatum','entlassungsort','bem'],main=detById(d.generatedFrom),draft={...d};
  if(main&&fields.every(k=>!d[k]))fields.forEach(k=>draft[k]=main[k]);
  return draft;
}
