const VIEW_NAMES={home:'Detachemente planen',persons:'Personen',groups:'Detachemente planen',orders:'Marschbefehle zuordnen',details:'Angaben ergänzen',pisa:'PISA-Abgleich',sources:'Datenquellen',files:'Projekte & Archiv',contacts:'Google-Kontakte'};
function btn(label,action,id='',primary=false){return `<button class="button${primary?' primary':''}" data-action="${action}" ${id?`data-id="${esc(id)}"`:''}>${label}</button>`;}
function navbtn(label,view,primary=false){return `<button class="button${primary?' primary':''}" data-nav="${view}">${label}</button>`;}
function badge(text,type=''){return `<span class="tag ${type}">${esc(text)}</span>`;}
function heading(title,sub,actions='',eyebrow='DIENSTLEISTUNG VORBEREITEN'){return `<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${esc(title)}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;}
function empty(title,text,actions=''){return `<div class="panel empty"><div class="empty-mark">▦</div><h2>${title}</h2><p>${text}</p><div class="actions">${actions}</div></div>`;}
function participationBadge(p){return badge(participationLabel(p),participation(p)==='unreviewed'?'warn':participation(p)==='excluded'?'neutral':'');}
function groupBadge(d){return badge(erfassungsStatus(d),erfasst(d)?'':'warn');}
function render(){
  $('#serviceName').textContent=S.name;$('#serviceDates').textContent=S.service.start?`${fmtDatum(S.service.start)} – ${fmtDatum(S.service.end)}`:'Dienstperiode noch offen';
  $('#breadcrumb').textContent=VIEW_NAMES[UI.view];$('#navPeople').textContent=S.persons.length;$('#navGroups').textContent=S.dets.length;$('#navPisa').textContent=S.dets.filter(d=>!erfasst(d)).length;
  $('#modeBadge').textContent=istArchiv()?'Archiv · schreibgeschützt':'In Vorbereitung';
  $$('.sidebar [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===(UI.view==='home'?'groups':UI.view)));
  const banner=istArchiv()?`<div class="notice archive info"><span><b>Archiv · ${esc(S.name)}</b><br>Stand vom ${zeitpunkt(S.archive.at)} · ${pisaGeprueft()?'PISA-Abschluss bestätigt':'PISA-Abschluss offen'}. Personen suchen und Aufgebote nachschlagen.</span>${btn('Als Arbeitskopie öffnen','resume')}</div>`:'';
  $('#main').innerHTML=banner+({home:viewHome,persons:viewPersons,groups:viewGroups,orders:viewOrders,details:viewDetails,pisa:viewPisa,sources:viewSources,files:viewFiles,contacts:viewContacts}[UI.view]||viewHome)();
}
function viewHome(){return istArchiv()?viewPersons():viewGroups();}

function task(n,title,text,action){return `<div class="task"><span class="task-number">${n}</span><div class="grow"><b>${title}</b><small>${text}</small></div>${action}</div>`;}
function stat(label,value,note){return `<div class="stat"><span class="eyebrow">${label}</span><b>${value}</b><small>${note}</small></div>`;}
function viewPersons(){
  const list=visiblePeople();if(!list.some(p=>p.id===UI.personId))UI.personId=list[0]?.id||null;
  return heading(istArchiv()?'Personen nachschlagen':'Personen','Eine Person, ein Dossier: Teilnahme, Hauptdetachement und alle Marschbefehlsdetails.',istArchiv()?'':btn('+ Person erfassen','person-new'),istArchiv()?'ARCHIV NACH PERSON':'PERSONAL & TEILNAHME')+
  `<div class="filters">${[['all','Alle'],['unreviewed','Teilnahme klären'],['included','Eingeplant'],['unassigned','Ohne Gruppe'],['excluded','Nicht eingeplant'],['issues','Prüfhinweise']].map(([key,label])=>`<button class="filter ${UI.filter===key?'active':''}" data-action="filter" data-id="${key}">${label}</button>`).join('')}</div><div class="count-note">${list.length} von ${S.persons.length} Personen${UI.query?' · Suche: '+esc(UI.query):''}</div>`+
  (!list.length?empty('Keine Personen gefunden',UI.query?'Suche ändern oder alle Filter zurücksetzen.':'Importiere einen Personalbestand oder wähle einen anderen Filter.',btn('Alle Personen anzeigen','clear-search')+(!S.persons.length?navbtn('Daten importieren','sources'):'')):
  `<div class="workspace"><section class="panel person-list" aria-label="Suchergebnisse">${list.map(p=>`<button class="list-item ${p.id===UI.personId?'active':''}" data-action="person" data-id="${esc(p.id)}"><span class="avatar">${esc(p.name.split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</span><span class="grow"><b>${esc(p.grad)} ${esc(p.name)}</b><small>${esc(p.pnr||'Versicherten-Nr. fehlt')} · ${esc(directGroups(p.id).map(d=>d.ec||'EC offen').join(', ')||'Ohne Hauptdetachement')}</small></span>${participation(p)==='unreviewed'?badge('Klären','warn'):''}</button>`).join('')}</section>${personDossier(pById(UI.personId))}</div>`);
}
function personDossier(p){
  const groups=detsVon(p.id),issues=personIssues(p);
  return `<article class="panel" aria-label="Personendossier"><div class="dossier-head"><span class="section-label">PERSONENDOSSIER · ${esc(personSource(p))}</span><h2>${esc(p.grad)} ${esc(p.name)}</h2><span class="muted mono">${esc(p.pnr||'Versicherten-Nr. nicht erfasst')}</span><p class="muted" style="margin:8px 0 0">${esc([fkt(p),p.einteilung].filter(Boolean).join(' · '))}</p><div class="actions">${participationBadge(p)}${istArchiv()?'':btn('Teilnahme & Zuteilung','person-edit',p.id)}${btn('Drucken','print')}</div></div>
  ${issues.length?`<details class="notice" style="margin:20px 24px"><summary>${issues.length} Prüfhinweise</summary><ul>${issues.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details>`:''}<div class="panel-head"><h3>Aufgebot & Marschbefehle</h3><span class="muted">${groups.length} EC</span></div><div style="height:20px"></div>${groups.map(d=>`<section class="mb-card"><div class="actions"><span class="ec">${esc(d.ec||'–')}</span><div class="grow"><b>${esc(d.name)}</b><small class="muted" style="display:block;margin-top:5px">${directGroups(p.id).some(g=>g.id===d.id)?'Hauptdetachement':'Zusatz-MB'}</small></div>${groupBadge(d)}</div><dl class="detail-grid">${detailWerte(d).slice(1).map(([l,v])=>detail(l,v,l==='Bemerkung MB')).join('')}</dl></section>`).join('')||'<p class="panel-body muted">Keine Einrückungsgruppe zugewiesen.</p>'}
  <div class="panel-head"><h3>Personendaten & Entscheid</h3></div><dl class="detail-grid">${detail('Funktion',fkt(p))}${detail('Einteilung',p.einteilung)}${detail('Zug / Element',p.zug)}${detail('Führerausweise',kats(p).join(', '))}${detail('Telefon',p.tel)}${detail('E-Mail',p.mail)}${p.planning?.reason?detail('Entscheid / Begründung',p.planning.reason,true):''}</dl><details class="raw-data"><summary>Übernommene Quelldaten anzeigen</summary><table><tbody>${Object.entries(p.raw||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')||'<tr><td>Keine weiteren Quelldaten.</td></tr>'}</tbody></table></details></article>`;
}
function detail(label,value,wide=false){return `<div${wide?' class="wide"':''}><dt>${esc(label)}</dt><dd>${esc(value||'—')}</dd></div>`;}
function groupList(selected,action){return `<section class="panel group-list">${S.dets.map(d=>`<button class="list-item ${selected===d.id?'active':''}" data-action="${action}" data-id="${esc(d.id)}"><span class="ec">${esc(d.ec||'–')}</span><span class="grow"><b>${esc(d.name||'Unbenannte Gruppe')}</b><small>${fmtDatum(d.datum)} · ${pisaPersonnel(d).length} Personen hinzufügen${!pisaPersonnel(d).length&&S.dets.some(g=>g.zusatzIds.includes(d.id))?' · Zusatz-MB':''}</small></span>${badge(erfasst(d)?'✓':pisaFehler(d).length?'!':'○',erfasst(d)?'':'warn')}</button>`).join('')}</section>`;}

function viewPisa(){
  const head=heading('Mit PISA abgleichen','Übertrage die vorbereiteten Angaben in PISA und bestätige danach den Abgleich. Die App meldet selbst nichts an PISA.','','MANUELLE ÜBERTRAGUNG');
  if(!S.dets.length)return head+empty('Noch keine Einrückungsgruppen','Bereite zuerst die Gruppen und ihre Personen vor.',navbtn('Gruppen anlegen','groups',true));
  const d=detById(UI.pisaId)||S.dets[0];UI.pisaId=d.id;const members=groupPeople(d),errors=pisaFehler(d),ready=isReady(),count=S.dets.filter(erfasst).length;
  const details=`<p class="muted">PISA: Marschbefehlsdetails des EC erfassen und mit diesen Angaben vergleichen.</p><dl>${detailWerte(d).map(([k,v])=>`<div class="copy-row"><dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd></div>`).join('')}</dl><div class="actions" style="margin-top:20px">${btn('Details kopieren','copy-details',d.id)}${istArchiv()?'':btn('Details bearbeiten','details-edit',d.id)}</div>`;
  const personnel=pisaPersonnelHtml(d);
  const confirm=`<h3>EC ${esc(d.ec||'offen')} in PISA kontrolliert?</h3><p class="muted">Bestätige erst, wenn Einrückungsdetails, Personal und Haupt-/Zusatz-MB in PISA mit diesem Stand übereinstimmen. Jede relevante Planänderung macht diese Bestätigung ungültig.</p>${errors.length?`<div class="notice"><b>Offene Einrückungsdetails</b><ul>${errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<p>${groupBadge(d)} ${S.pisa.entered[d.id]?`<small class="muted">Letzte Bestätigung: ${zeitpunkt(S.pisa.entered[d.id].at)}</small>`:''}</p>${istArchiv()?'':`<button class="button primary" data-action="confirm-group" data-id="${esc(d.id)}" ${errors.length||!members.length?'disabled':''}>Abgleich dieses EC bestätigen</button>`}`;
  return workflowSteps('pisa')+head+`<section class="panel panel-body"><div class="actions"><b>${count} von ${S.dets.length} EC abgeglichen</b><span style="margin-left:auto">${badge(pisaGeprueft()?'Abschluss geprüft':'Abschluss offen',pisaGeprueft()?'':'warn')}</span></div><div class="progress"><span style="width:${count/S.dets.length*100}%"></span></div><small class="muted">${ready?'Alle lokalen Pflichtprüfungen sind erledigt.':'Teilnahme, Identitäten, Zuteilungen, belegte Gruppen und vollständige Details müssen vor dem Abschluss geklärt sein.'}</small>${pisaBlockers()}</section><div class="workspace">${groupList(d.id,'pisa-group')}<article class="panel"><div class="panel-head"><h2>EC ${esc(d.ec||'–')} · ${esc(d.name)}</h2>${groupBadge(d)}</div><div class="steps">${[['details','1 · Details'],['persons','2 · Personal & Zusatz-MB'],['confirm','3 · Bestätigen']].map(([key,t])=>`<button class="${UI.pisaStep===key?'active':''}" data-action="pisa-step" data-id="${key}">${t}</button>`).join('')}</div><div class="panel-body">${UI.pisaStep==='details'?details:UI.pisaStep==='persons'?personnel:confirm}</div></article></div><section class="panel panel-body"><h2>Überprüfung, Genehmigung & Verarbeitung</h2><p class="muted">Zum Abschluss den Auftrag in PISA überprüfen/genehmigen und dessen Verarbeitung kontrollieren. Diese Bestätigung hält nur deinen manuellen Kontrollstand fest.</p><div class="actions">${istArchiv()?'':`<button class="button primary" data-action="verify" ${ready?'':'disabled'}>Abschluss in PISA geprüft</button>`}${pisaGeprueft()&&!istArchiv()?btn('Plan archivieren','archive'):''}${btn('Offene Punkte ansehen','filter','issues')}</div></section>`;
}
function viewSources(){return heading('Datenquellen','Personalbestand übernehmen, Identitäten abgleichen und danach die Teilnahme jeder Person festlegen.',istArchiv()?'':btn('Person manuell erfassen','person-new'),'GRUNDLAGEN')+`<div class="notice info">PISA 401, PISA 410 und DVM können unterschiedliche Personenkreise enthalten. Eine importierte Person wird deshalb zunächst als «Teilnahme klären» geführt. Eine eindeutige Versicherten-Nr. verbindet die Quellen.</div><div class="columns">${['pisa','milo'].map(q=>`<section class="panel panel-body"><span class="section-label">PERSONALBESTAND</span><h2>${q==='pisa'?'PISA':'MILOFFICE'}</h2><p class="muted">${q==='pisa'?'Personalstammdaten und Angaben aus der PISA-Liste.':'Ergänzende Funktionen, Kontaktangaben und Führerausweise.'}</p>${S.src[q]?`<p><b>${esc(S.src[q].datei)}</b><br><small class="muted">${zeitpunkt(S.src[q].zeit)} · ${S.src[q].anz} Zeilen</small></p>`:'<p class="muted">Noch keine Liste übernommen.</p>'}${istArchiv()?'':btn('Excel / CSV importieren','import',q,true)}</section>`).join('')}</div><section class="panel panel-body"><h2>Quellenabgleich prüfen</h2><p class="muted">Personen werden anhand einer eindeutigen Versicherten-Nr. ergänzt. Ein optionaler Namensabgleich muss anschliessend im Personendossier bestätigt werden. Gleichnamige Personen mit unterschiedlichen Nummern bleiben getrennt.</p><div class="actions">${btn('Teilnahme klären','filter','unreviewed')}${btn('Prüfhinweise ansehen','filter','issues')}${istArchiv()?'':btn('Kurzformen bearbeiten','mappings')}</div></section>`;}
function viewFiles(){
  let list=[],error='';try{list=archiveLibrary();}catch(e){error=e.message;}const query=norm(UI.archiveQuery);list=list.filter(x=>!query||norm(x.name).includes(query)||x.persons.some(p=>norm(p.name+' '+(p.pnr||'')).includes(query)));
  return heading('Projekte & Archiv','Eine Dienstleistung vorbereiten, ihren Abschluss aufbewahren und später gezielt nachschlagen.',btn('Projektdatei öffnen','load-file'),'LOKALE ABLAGE')+`<div class="columns"><section class="panel panel-body"><span class="section-label">AKTUELLES PROJEKT</span><h2>${esc(S.name)}</h2><p class="muted">${esc(S.settings.eigeneEinheit||'Einheit offen')}<br>${fmtDatum(S.service.start)} – ${fmtDatum(S.service.end)}<br>${S.persons.length} Personen · ${S.dets.length} Einrückungsgruppen</p><div class="actions">${istArchiv()?btn('Arbeitskopie erstellen','resume'):btn('Dienstleistung bearbeiten','service')+btn('Plan archivieren','archive')}</div></section><section class="panel panel-body"><span class="section-label">SICHERN & WEITERGEBEN</span><h2>Dein Projekt als Datei</h2><p class="muted">Die Browserablage gehört zu diesem Gerät. Sichere eine Projektdatei, um einen Stand unabhängig davon aufzubewahren.</p><div class="actions">${btn('Projektdatei (.json)','save-file','',true)}${btn('App mit Daten (.html)','export-html')}${btn('Arbeitsliste (.xlsx)','export-xlsx')}${navbtn('Google-Kontakte vorbereiten','contacts')}</div></section></div><section class="panel"><div class="panel-head"><div><h2>Archivierte Dienstleistungen</h2><small class="muted">Lokale Planstände · kein PISA-Einheitsarchiv</small></div>${btn('+ Neue Dienstleistung','new-project')}</div>${error?`<div class="notice">${esc(error)}</div>`:''}<div class="panel-body" style="padding-bottom:0"><input type="search" id="archiveSearch" aria-label="Alle Archive durchsuchen" placeholder="Dienstleistung, Person oder Versicherten-Nr. suchen…" value="${esc(UI.archiveQuery)}"></div><div class="archive-list">${list.map(x=>`<div class="task"><span class="ec">▤</span><div class="grow"><b>${esc(x.name)}</b><small>${zeitpunkt(x.archive.at)} · ${x.persons.length} Personen · ${x.dets.length} EC${query?' · '+esc(x.persons.filter(p=>norm(p.name+' '+(p.pnr||'')).includes(query)).map(p=>p.name).join(', ')):''}</small></div>${btn('Personen nachschlagen','open-archive',x.archive.id)}</div>`).join('')||`<div class="empty"><h3>${query?'Keine passenden Archivstände':'Noch keine archivierte Dienstleistung'}</h3><p>Archivierte Pläne bleiben schreibgeschützt. Für Änderungen erstellst du eine separate Arbeitskopie.</p></div>`}</div></section>`;
}

function pisaBlockers(){const v=validationSummary();const rows=[['Teilnahme klären',v.unreviewed.length,'persons'],['Ohne Hauptdetachement',v.unassigned.length,'persons'],['Identitäten prüfen',v.identity.length+v.duplicateNumbers.length,'persons'],['Zuteilung / Entscheid klären',v.multiple.length+v.excludedAssigned.length+v.excludedReason.length,'persons'],['Gruppendetails ergänzen',v.groupErrors.length,'groups'],['Unbelegte Gruppen',v.empty.length,'groups'],['Fehlende Personenreferenzen',v.dangling.length,'groups']].filter(([,n])=>n);return rows.length?'<div class="actions" style="margin-top:15px">'+rows.map(([t,n,view])=>view==='persons'?btn(`${n} · ${t}`,'filter','issues'):navbtn(`${n} · ${t}`,view==='groups'?'details':view)).join('')+'</div>':'';}
